### ISSUE TITLE
Bug: Invalid value for CURRENT_CLUSTER_PORT when the .kube/config files was generated by the AWS CLI

### ISSUE THREAD

**Issue by JPLachance** [strongdm/resource-registration-scripts#1]
### Issue

We use the AWS CLI to generate the .kube/config file. By doing so, the generated context does not mention any port.

The line https://github.com/strongdm/resource-registration-scripts/blob/main/k8s-sa-and-cluster-registration-in-sdm.sh#L26 is therefore not finding one, which leads to an empty value for CURRENT_CLUSTER_PORT.

The empty value for CURRENT_CLUSTER_PORT is later then not accepted by the `sdm admin clusters add k8s-service` command.

### Expectation

A customer of this script would ideally not need to modify it prior to use.

**Comment by dbinger** [comment]
Thanks for the report.  Should be fixed now in v1.0.1.
